---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: docker.io/library/backend:local
        name: app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
  selector:
    app: app