---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-image-pull-secret
      containers:
      - image: 382942022480.dkr.ecr.us-east-1.amazonaws.com/backend-dev:6711de2f55268fedac3217e8162fe5eec174cc59
        name: backend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-image-pull-secret
      containers:
      - image: 382942022480.dkr.ecr.us-east-1.amazonaws.com/frontend-dev:7985561368690ae1dec1855b9c14ad80348bc64d
        name: frontend
        ports:
        - containerPort: 3001
        env:
          - name: API_ENDPOINT
            value: "http://backend.default.svc:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  type: ClusterIP
  selector:
    app: frontend